import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Shared/Navbar";



const open_Sans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${open_Sans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
