import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Shared/Navbar";
import Footer from "@/Components/Shared/Footer";
import SplashScreen from "@/Components/SplashScreen/SplashScreen";
import LenisProvider from "@/Components/LanisProvider/LanisProvider";




const open_Sans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${open_Sans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>

        <SplashScreen>
          <LenisProvider>
            <main className="grow">
           
                {children}
            

            </main>
          </LenisProvider>
        </SplashScreen>
        <Footer></Footer>
      </body>
    </html>
  );
}
